
version: '3.4'

services:

  dicom:
    build:
      context: ./
    environment:
      TZ: 'Europe/London'
      DATABASE_HOST: "host.docker.internal"
      DATABASE_USER: "${DATABASE_USER:-openeyes}"
      DATABASE_PASS: "${DATABASE_PASS:-openeyes}"
      
    stdin_open: true
    tty: true

