name: Publish Docker image

on:
  push:
    branches:
      - "master"
      - "main"
      - "develop"
      - "bugfix/**"
      - "release/**"
    tags:
      - "*"
env:
  DOCKER_ORG: "toukanlabsdocker"
  DOCKER_IMAGE: "payloadprocessor"
  IMAGE_SUFFIX: ""

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Resolve ref
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup metadata for docker image tags
        id: meta
        uses: toukanlabs/build-tag-gen@v3
        with:
          image-name: ${{ env.DOCKER_ORG }}/${{ env.DOCKER_IMAGE }}
          slug: ${{ env.GITHUB_REF_SLUG }}
          suffix: ${{ env.IMAGE_SUFFIX }}
          docker-user: ${{ secrets.DOCKER_USERNAME }}
          docker-pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-docker-hub-description:
    name: Update docker hub description
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_ORG }}/${{ env.DOCKER_IMAGE }}
